### DISCUSSION TITLE
Extract shape definitions and ISOM code to shape mapping into config files

### DISCUSSION THREAD

**Discussion by vbrandl** [karttapullautin/karttapullautin#119] [Ideas]
Hey,

What do you think about introducing a config file where we can define different objects and how to draw them, e.g.

```toml
[526] # building
shape = "polygon"
color = "black"
border_width = "..."
border_color = "..."

[<isom code>] # tree
shape = "point"
color = "..."
border_color = "..."
width = "..."
border_witdh = "..."

[<isom code>] # road
shape = "line"
color = "..."
width = "..."
```

This way, if the ISOM specification changes, how certain objects should be drawn, it doesn't need any changes in the code, just the configuration. Also each version of the tool could (depending on which object configuration is used) draw maps in older ISOM styles. And we could add ISSprOM styled objects without any changes to the code.

Would you be interested in something like this? If so, I might start with defining all required shapes and how to render them.

Also I saw, you are currently refactoring the code. Do you need help with that?
